package io.github.chris2011.netbeans.minifierbeans.javascript.ui.options;

import javax.swing.JPanel;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import org.netbeans.spi.options.OptionsPanelController;
import org.openide.util.NbBundle;

@OptionsPanelController.Keywords(keywords={"js", "#JsOptionsPanel.Keyword1", "#JsOptionsPanel.Keyword2"},
        location="Html5", tabTitle="#CTL_OptionsPanel.title")
@NbBundle.Messages({
    "CTL_OptionsPanel.title=Minification",
    "JsOptionsPanel.Keyword1=Minify JavaScript",
    "JsOptionsPanel.Keyword2=Minify JavaScript on save"
})
public final class JsOptionsPanel extends JPanel {
    private String[] keywords;

    public JsOptionsPanel() {
        initComponents();

        headerLabelJs.setVisible(false);
        headerScrollPaneJs.setVisible(false);
        txtHeaderEditorPaneJs.setVisible(false);
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
    }

    @Override
    public void removeNotify() {
        super.removeNotify();
    }

    public Collection<String> getKeywords () {
        if (keywords == null) {
            keywords = new String[] {
                "JavaScript",
                Bundle.JsOptionsPanel_Keyword1().toUpperCase(),
                Bundle.JsOptionsPanel_Keyword2().toUpperCase()
            };
        }

        return Collections.unmodifiableList(Arrays.asList(keywords));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closureCompilerLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chbMinifyOnSave = new javax.swing.JCheckBox();
        chbGenerateNewJsFile = new javax.swing.JCheckBox();
        txtJsPreExtension = new javax.swing.JTextField();
        extLabel = new javax.swing.JLabel();
        closureCompilerFlagsLabel = new javax.swing.JLabel();
        txtClosureCompilerFlagsTextField = new javax.swing.JTextField();
        closureCompilerArgumentsHintsLabel = new javax.swing.JLabel();
        headerLabelJs = new javax.swing.JLabel();
        headerScrollPaneJs = new javax.swing.JScrollPane();
        txtHeaderEditorPaneJs = new javax.swing.JEditorPane();

        org.openide.awt.Mnemonics.setLocalizedText(closureCompilerLabel, org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.closureCompilerLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closureCompilerLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closureCompilerLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(762, 86));

        chbMinifyOnSave.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(chbMinifyOnSave, org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.chbMinifyOnSave.text")); // NOI18N
        chbMinifyOnSave.setContentAreaFilled(false);

        chbGenerateNewJsFile.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(chbGenerateNewJsFile, org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.chbGenerateNewJsFile.text")); // NOI18N
        chbGenerateNewJsFile.setContentAreaFilled(false);

        txtJsPreExtension.setText(org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.txtJsPreExtension.text")); // NOI18N

        extLabel.setForeground(extLabel.getForeground().darker());
        org.openide.awt.Mnemonics.setLocalizedText(extLabel, org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.extLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(closureCompilerFlagsLabel, org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.closureCompilerFlagsLabel.text")); // NOI18N

        txtClosureCompilerFlagsTextField.setText(org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.txtClosureCompilerFlagsTextField.text")); // NOI18N

        closureCompilerArgumentsHintsLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(closureCompilerArgumentsHintsLabel, org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.closureCompilerArgumentsHintsLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbGenerateNewJsFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJsPreExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extLabel))
                    .addComponent(chbMinifyOnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(closureCompilerFlagsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closureCompilerArgumentsHintsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClosureCompilerFlagsTextField))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closureCompilerFlagsLabel)
                    .addComponent(txtClosureCompilerFlagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closureCompilerArgumentsHintsLabel)
                .addGap(18, 18, 18)
                .addComponent(chbMinifyOnSave)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbGenerateNewJsFile)
                    .addComponent(extLabel)
                    .addComponent(txtJsPreExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(headerLabelJs, org.openide.util.NbBundle.getMessage(JsOptionsPanel.class, "JsOptionsPanel.headerLabelJs.text")); // NOI18N

        txtHeaderEditorPaneJs.setContentType("text/javascript"); // NOI18N
        headerScrollPaneJs.setViewportView(txtHeaderEditorPaneJs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addComponent(headerLabelJs)
                    .addComponent(headerScrollPaneJs, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headerLabelJs)
                .addGap(6, 6, 6)
                .addComponent(headerScrollPaneJs, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chbGenerateNewJsFile;
    public javax.swing.JCheckBox chbMinifyOnSave;
    private javax.swing.JLabel closureCompilerArgumentsHintsLabel;
    private javax.swing.JLabel closureCompilerFlagsLabel;
    private javax.swing.JLabel closureCompilerLabel;
    private javax.swing.JLabel extLabel;
    private javax.swing.JLabel headerLabelJs;
    private javax.swing.JScrollPane headerScrollPaneJs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtClosureCompilerFlagsTextField;
    protected javax.swing.JEditorPane txtHeaderEditorPaneJs;
    public javax.swing.JTextField txtJsPreExtension;
    // End of variables declaration//GEN-END:variables
}
