/**
 * Copyright [2013] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.minify.ui;
 class JSCSSMinifyCompressPanel extends javax.swing.JPanel {

    public final JSCSSMinifyCompressOptionsPanelController controller;

  public JSCSSMinifyCompressPanel(JSCSSMinifyCompressOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        
        
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        newJSFile = new javax.swing.JCheckBox();
        jsObfuscate = new javax.swing.JCheckBox();
        separatorJS_Label = new javax.swing.JLabel();
        preExtensionJS = new javax.swing.JTextField();
        preExtensionJS_Label = new javax.swing.JLabel();
        separatorJS = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        newCSSFile = new javax.swing.JCheckBox();
        separatorCSS_Label = new javax.swing.JLabel();
        preExtensionCSS = new javax.swing.JTextField();
        preExtensionCSS_Label = new javax.swing.JLabel();
        separatorCSS = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        separatBuild = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        buildJSMinify = new javax.swing.JCheckBox();
        buildCSSMinify = new javax.swing.JCheckBox();
        skipPreExtensionJS = new javax.swing.JCheckBox();
        skipPreExtensionCSS = new javax.swing.JCheckBox();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.jLabel3.text")); // NOI18N
        jLabel3.setBounds(30, 10, 210, 22);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(newJSFile, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.newJSFile.text")); // NOI18N
        newJSFile.setToolTipText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.newJSFile.toolTipText")); // NOI18N
        newJSFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newJSFileActionPerformed(evt);
            }
        });
        newJSFile.setBounds(50, 40, 140, 23);
        jLayeredPane1.add(newJSFile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(jsObfuscate, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.jsObfuscate.text")); // NOI18N
        jsObfuscate.setBounds(50, 70, 89, 23);
        jLayeredPane1.add(jsObfuscate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(separatorJS_Label, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatorJS_Label.text")); // NOI18N
        separatorJS_Label.setBounds(200, 70, 140, 20);
        jLayeredPane1.add(separatorJS_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        preExtensionJS.setText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.preExtensionJS.text")); // NOI18N
        preExtensionJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preExtensionJSActionPerformed(evt);
            }
        });
        preExtensionJS.setBounds(340, 40, 50, 20);
        jLayeredPane1.add(preExtensionJS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(preExtensionJS_Label, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.preExtensionJS_Label.text")); // NOI18N
        preExtensionJS_Label.setBounds(205, 40, 130, 20);
        jLayeredPane1.add(preExtensionJS_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        separatorJS.setText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatorJS.text")); // NOI18N
        separatorJS.setToolTipText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatorJS.toolTipText")); // NOI18N
        separatorJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                separatorJSActionPerformed(evt);
            }
        });
        separatorJS.setBounds(340, 70, 50, 20);
        jLayeredPane1.add(separatorJS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.jLabel4.text")); // NOI18N
        jLabel4.setBounds(30, 20, 170, 25);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(newCSSFile, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.newCSSFile.text")); // NOI18N
        newCSSFile.setToolTipText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.newCSSFile.toolTipText")); // NOI18N
        newCSSFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCSSFileActionPerformed(evt);
            }
        });
        newCSSFile.setBounds(50, 50, 123, 23);
        jLayeredPane2.add(newCSSFile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(separatorCSS_Label, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatorCSS_Label.text")); // NOI18N
        separatorCSS_Label.setBounds(210, 80, 130, 20);
        jLayeredPane2.add(separatorCSS_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        preExtensionCSS.setText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.preExtensionCSS.text")); // NOI18N
        preExtensionCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preExtensionCSSActionPerformed(evt);
            }
        });
        preExtensionCSS.setBounds(340, 50, 50, 20);
        jLayeredPane2.add(preExtensionCSS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(preExtensionCSS_Label, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.preExtensionCSS_Label.text")); // NOI18N
        preExtensionCSS_Label.setBounds(210, 50, 113, 20);
        jLayeredPane2.add(preExtensionCSS_Label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        separatorCSS.setText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatorCSS.text")); // NOI18N
        separatorCSS.setToolTipText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatorCSS.toolTipText")); // NOI18N
        separatorCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                separatorCSSActionPerformed(evt);
            }
        });
        separatorCSS.setBounds(340, 80, 50, 20);
        jLayeredPane2.add(separatorCSS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.jLabel5.text")); // NOI18N
        jLabel5.setBounds(30, 10, 180, 15);
        jLayeredPane3.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.jLabel6.text")); // NOI18N
        jLabel6.setBounds(230, 10, 168, 14);
        jLayeredPane3.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(separatBuild, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatBuild.text")); // NOI18N
        separatBuild.setToolTipText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatBuild.toolTipText")); // NOI18N
        separatBuild.setActionCommand(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.separatBuild.actionCommand")); // NOI18N
        separatBuild.setBounds(50, 40, 163, 23);
        jLayeredPane3.add(separatBuild, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.jLabel7.text")); // NOI18N
        jLabel7.setBounds(50, 80, 292, 13);
        jLayeredPane3.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(buildJSMinify, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.buildJSMinify.text")); // NOI18N
        buildJSMinify.setBounds(50, 100, 67, 23);
        jLayeredPane3.add(buildJSMinify, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(buildCSSMinify, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.buildCSSMinify.text")); // NOI18N
        buildCSSMinify.setBounds(50, 130, 75, 23);
        jLayeredPane3.add(buildCSSMinify, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(skipPreExtensionJS, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.skipPreExtensionJS.text")); // NOI18N
        skipPreExtensionJS.setToolTipText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.skipPreExtensionJS.toolTipText")); // NOI18N
        skipPreExtensionJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipPreExtensionJSActionPerformed(evt);
            }
        });
        skipPreExtensionJS.setBounds(210, 100, 250, 23);
        jLayeredPane3.add(skipPreExtensionJS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(skipPreExtensionCSS, org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.skipPreExtensionCSS.text")); // NOI18N
        skipPreExtensionCSS.setToolTipText(org.openide.util.NbBundle.getMessage(JSCSSMinifyCompressPanel.class, "JSCSSMinifyCompressPanel.skipPreExtensionCSS.toolTipText")); // NOI18N
        skipPreExtensionCSS.setBounds(210, 130, 230, 23);
        jLayeredPane3.add(skipPreExtensionCSS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane2))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void preExtensionJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preExtensionJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preExtensionJSActionPerformed

    public void newJSFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newJSFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newJSFileActionPerformed

    public void newCSSFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCSSFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCSSFileActionPerformed

    public void preExtensionCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preExtensionCSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preExtensionCSSActionPerformed

    public void skipPreExtensionJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipPreExtensionJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skipPreExtensionJSActionPerformed

    private void separatorJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_separatorJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_separatorJSActionPerformed

    private void separatorCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_separatorCSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_separatorCSSActionPerformed
  
    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(JSCSSMinifyCompressPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(JSCSSMinifyCompressPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(JSCSSMinifyCompressPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(JSCSSMinifyCompressPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox buildCSSMinify;
    public javax.swing.JCheckBox buildJSMinify;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    public javax.swing.JCheckBox jsObfuscate;
    public javax.swing.JCheckBox newCSSFile;
    public javax.swing.JCheckBox newJSFile;
    public javax.swing.JTextField preExtensionCSS;
    public javax.swing.JLabel preExtensionCSS_Label;
    public javax.swing.JTextField preExtensionJS;
    public javax.swing.JLabel preExtensionJS_Label;
    public javax.swing.JCheckBox separatBuild;
    public javax.swing.JTextField separatorCSS;
    public javax.swing.JLabel separatorCSS_Label;
    public javax.swing.JTextField separatorJS;
    public javax.swing.JLabel separatorJS_Label;
    public javax.swing.JCheckBox skipPreExtensionCSS;
    public javax.swing.JCheckBox skipPreExtensionJS;
    // End of variables declaration//GEN-END:variables
}
