package io.github.chris2011.netbeans.minifierbeans.html.ui.options;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JPanel;
import org.netbeans.spi.options.OptionsPanelController;
import org.openide.util.NbBundle;

@OptionsPanelController.Keywords(keywords={"html", "#HtmlOptionsPanel.Keyword1", "#HtmlOptionsPanel.Keyword2"},
        location="Html5", tabTitle="#CTL_OptionsPanel.title")
@NbBundle.Messages({
    "CTL_OptionsPanel.title=Minification",
    "HtmlOptionsPanel.Keyword1=Minify HTML",
    "HtmlOptionsPanel.Keyword2=Minify HTML on save"
})
public final class HtmlOptionsPanel extends JPanel {
    private String[] keywords;

    public HtmlOptionsPanel() {
        initComponents();
        
        headerLabelHtml.setVisible(false);
        headerScrollPaneHtml.setVisible(false);
        txtHeaderEditorPaneHtml.setVisible(false);
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
    }

    @Override
    public void removeNotify() {
        super.removeNotify();
    }

    public Collection<String> getKeywords () {
        if (keywords == null) {
            keywords = new String[] {
                "HTML",
                Bundle.HtmlOptionsPanel_Keyword1().toUpperCase(),
                Bundle.HtmlOptionsPanel_Keyword2().toUpperCase()
            };
        }

        return Collections.unmodifiableList(Arrays.asList(keywords));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        htmlMinifierLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chbGenerateNewHtmlFile = new javax.swing.JCheckBox();
        txtHtmlPreExtension = new javax.swing.JTextField();
        chbMinifyHtmlOnSave = new javax.swing.JCheckBox();
        extLabel = new javax.swing.JLabel();
        htmlMinifierFlagsLabel = new javax.swing.JLabel();
        txtHtmlMinifierFlags = new javax.swing.JTextField();
        htmlMinifierFlagsHintsLabel = new javax.swing.JLabel();
        headerLabelHtml = new javax.swing.JLabel();
        headerScrollPaneHtml = new javax.swing.JScrollPane();
        txtHeaderEditorPaneHtml = new javax.swing.JEditorPane();

        setPreferredSize(new java.awt.Dimension(768, 314));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 32));

        org.openide.awt.Mnemonics.setLocalizedText(htmlMinifierLabel, org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.htmlMinifierLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(htmlMinifierLabel)
                .addGap(0, 223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(htmlMinifierLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(762, 86));

        chbGenerateNewHtmlFile.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(chbGenerateNewHtmlFile, org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.chbGenerateNewHtmlFile.text")); // NOI18N
        chbGenerateNewHtmlFile.setContentAreaFilled(false);

        txtHtmlPreExtension.setText(org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.txtHtmlPreExtension.text")); // NOI18N

        chbMinifyHtmlOnSave.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(chbMinifyHtmlOnSave, org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.chbMinifyHtmlOnSave.text")); // NOI18N
        chbMinifyHtmlOnSave.setContentAreaFilled(false);

        extLabel.setForeground(extLabel.getForeground().darker());
        org.openide.awt.Mnemonics.setLocalizedText(extLabel, org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.extLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(htmlMinifierFlagsLabel, org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.htmlMinifierFlagsLabel.text")); // NOI18N

        txtHtmlMinifierFlags.setText(org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.txtHtmlMinifierFlags.text")); // NOI18N

        htmlMinifierFlagsHintsLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(htmlMinifierFlagsHintsLabel, org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.htmlMinifierFlagsHintsLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbMinifyHtmlOnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbGenerateNewHtmlFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHtmlPreExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(htmlMinifierFlagsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(htmlMinifierFlagsHintsLabel)
                            .addComponent(txtHtmlMinifierFlags, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(htmlMinifierFlagsLabel)
                    .addComponent(txtHtmlMinifierFlags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(htmlMinifierFlagsHintsLabel)
                .addGap(18, 18, 18)
                .addComponent(chbMinifyHtmlOnSave)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbGenerateNewHtmlFile)
                    .addComponent(txtHtmlPreExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(headerLabelHtml, org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.headerLabelHtml.text")); // NOI18N

        txtHeaderEditorPaneHtml.setContentType("text/html"); // NOI18N
        txtHeaderEditorPaneHtml.setText(org.openide.util.NbBundle.getMessage(HtmlOptionsPanel.class, "HtmlOptionsPanel.txtHeaderEditorPaneHtml.text")); // NOI18N
        headerScrollPaneHtml.setViewportView(txtHeaderEditorPaneHtml);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerLabelHtml)
                            .addComponent(headerScrollPaneHtml, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabelHtml)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerScrollPaneHtml, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chbGenerateNewHtmlFile;
    public javax.swing.JCheckBox chbMinifyHtmlOnSave;
    private javax.swing.JLabel extLabel;
    private javax.swing.JLabel headerLabelHtml;
    private javax.swing.JScrollPane headerScrollPaneHtml;
    private javax.swing.JLabel htmlMinifierFlagsHintsLabel;
    private javax.swing.JLabel htmlMinifierFlagsLabel;
    private javax.swing.JLabel htmlMinifierLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    protected javax.swing.JEditorPane txtHeaderEditorPaneHtml;
    javax.swing.JTextField txtHtmlMinifierFlags;
    public javax.swing.JTextField txtHtmlPreExtension;
    // End of variables declaration//GEN-END:variables
}
