package io.github.chris2011.netbeans.minifierbeans.css.ui.options;

import io.github.chris2011.netbeans.minifierbeans.util.RoundButton;
import java.awt.FlowLayout;
import javax.swing.JPanel;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import org.netbeans.spi.options.OptionsPanelController;
import org.openide.util.NbBundle;

@OptionsPanelController.Keywords(keywords = {"css", "#CssOptionsPanel.Keyword1", "#CssOptionsPanel.Keyword2"},
    location = "Html5", tabTitle = "#CTL_OptionsPanel.title")
@NbBundle.Messages({
    "CTL_OptionsPanel.title=Minification",
    "CssOptionsPanel.Keyword1=Minify CSS",
    "CssOptionsPanel.Keyword2=Minify CSS on save"
})
public final class CssOptionsPanel extends JPanel {
    private String[] keywords;
    public RoundButton btnHeaderContentHelp = new RoundButton(null, 75);

    public CssOptionsPanel() {
        initComponents();

        pnlFixedHeaderContentHelp.setLayout(new FlowLayout());
        pnlFixedHeaderContentHelp.add(btnHeaderContentHelp);
        
        jPanel3.setVisible(false);
//        pnlFixedHeaderContentHelp.setVisible(false);
//        txtHeaderEditorPaneCss.setVisible(false);
//        lblHeaderEditorPaneCss.setVisible(false);
    }

    @Override
    public void addNotify() {
        super.addNotify();
    }

    @Override
    public void removeNotify() {
        super.removeNotify();
    }

    public Collection<String> getKeywords() {
        if (keywords == null) {
            keywords = new String[]{
                "CSS",
                Bundle.CssOptionsPanel_Keyword1().toUpperCase(),
                Bundle.CssOptionsPanel_Keyword2().toUpperCase()
            };
        }

        return Collections.unmodifiableList(Arrays.asList(keywords));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cssNanoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        extLabel = new javax.swing.JLabel();
        txtCssPreExtension = new javax.swing.JTextField();
        chbMinifyCssOnSave = new javax.swing.JCheckBox();
        chbGenerateNewCssFile = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        pnlFixedHeaderContentHelp = new javax.swing.JPanel();
        lblHeaderEditorPaneCss = new javax.swing.JLabel();
        headerScrollPaneCSS = new javax.swing.JScrollPane();
        txtHeaderEditorPaneCss = new javax.swing.JEditorPane();

        cssNanoLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(cssNanoLabel, org.openide.util.NbBundle.getMessage(CssOptionsPanel.class, "CssOptionsPanel.cssNanoLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cssNanoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cssNanoLabel)
                .addGap(68, 68, 68))
        );

        extLabel.setForeground(extLabel.getForeground().darker());
        org.openide.awt.Mnemonics.setLocalizedText(extLabel, org.openide.util.NbBundle.getMessage(CssOptionsPanel.class, "CssOptionsPanel.extLabel.text")); // NOI18N

        txtCssPreExtension.setText(org.openide.util.NbBundle.getMessage(CssOptionsPanel.class, "CssOptionsPanel.txtCssPreExtension.text")); // NOI18N

        chbMinifyCssOnSave.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(chbMinifyCssOnSave, org.openide.util.NbBundle.getMessage(CssOptionsPanel.class, "CssOptionsPanel.chbMinifyCssOnSave.text")); // NOI18N
        chbMinifyCssOnSave.setContentAreaFilled(false);

        chbGenerateNewCssFile.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(chbGenerateNewCssFile, org.openide.util.NbBundle.getMessage(CssOptionsPanel.class, "CssOptionsPanel.chbGenerateNewCssFile.text")); // NOI18N
        chbGenerateNewCssFile.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbMinifyCssOnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbGenerateNewCssFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCssPreExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(chbMinifyCssOnSave)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCssPreExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(extLabel))
                    .addComponent(chbGenerateNewCssFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFixedHeaderContentHelpLayout = new javax.swing.GroupLayout(pnlFixedHeaderContentHelp);
        pnlFixedHeaderContentHelp.setLayout(pnlFixedHeaderContentHelpLayout);
        pnlFixedHeaderContentHelpLayout.setHorizontalGroup(
            pnlFixedHeaderContentHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnlFixedHeaderContentHelpLayout.setVerticalGroup(
            pnlFixedHeaderContentHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(lblHeaderEditorPaneCss, org.openide.util.NbBundle.getMessage(CssOptionsPanel.class, "CssOptionsPanel.lblHeaderEditorPaneCss.text")); // NOI18N

        txtHeaderEditorPaneCss.setContentType("text/css");
        headerScrollPaneCSS.setViewportView(txtHeaderEditorPaneCss);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblHeaderEditorPaneCss)
                .addGap(214, 214, 214)
                .addComponent(pnlFixedHeaderContentHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerScrollPaneCSS, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeaderEditorPaneCss)
                    .addComponent(pnlFixedHeaderContentHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(headerScrollPaneCSS, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox chbGenerateNewCssFile;
    public javax.swing.JCheckBox chbMinifyCssOnSave;
    private javax.swing.JLabel cssNanoLabel;
    private javax.swing.JLabel extLabel;
    private javax.swing.JScrollPane headerScrollPaneCSS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblHeaderEditorPaneCss;
    private javax.swing.JPanel pnlFixedHeaderContentHelp;
    public javax.swing.JTextField txtCssPreExtension;
    protected javax.swing.JEditorPane txtHeaderEditorPaneCss;
    // End of variables declaration//GEN-END:variables
}
